// Package service provides facade services that orchestrate the multi-step
// data flows required by each CLI command. Each facade exposes a single Run
// method so that command handlers contain no business logic.
//
// AnalysisFacade and BenchmarkFacade are the primary contracts consumed by the
// cmd/ layer. Concrete implementations live in analysis.go and benchmark.go.
package service

import (
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"time"

	"github.com/JamesOlaitan/accessgraph/internal/analyzer"
	"github.com/JamesOlaitan/accessgraph/internal/graph"
	"github.com/JamesOlaitan/accessgraph/internal/model"
	"github.com/JamesOlaitan/accessgraph/internal/policy"
	"github.com/JamesOlaitan/accessgraph/internal/report"
	"github.com/JamesOlaitan/accessgraph/internal/store"
)

// ErrInvalidInput is returned by facade methods when a caller-supplied parameter
// fails a precondition check (e.g., an unsupported output format).
var ErrInvalidInput = errors.New("invalid input")

// AnalysisFacade orchestrates the full analyze pipeline as a single operation.
// It is the only type that calls parser, graph, analyzer, policy, store, and
// renderer in sequence. The analyze command calls exactly one method on this
// facade.
//
// Returns ErrInvalidInput if format is not one of {terminal, json, dot}. This
// check is performed before any store or graph operations so callers receive a
// fast, clean error for bad flag values.
type AnalysisFacade interface {
	// Run executes the full analysis pipeline: load snapshot → build graph →
	// synthesize escalation edges → resolve principal → blast-radius BFS →
	// OPA evaluation (degraded) → persist → render.
	//
	// Parameters:
	//   - ctx: context for cancellation.
	//   - snapshotLabel: human-readable label used to load the snapshot.
	//   - principalARN: ARN of the compromised starting principal.
	//   - maxHops: maximum BFS depth; must be >= 1.
	//   - format: output format — "terminal", "json", or "dot".
	//   - w: destination for the rendered report.
	//
	// Errors:
	//   - ErrInvalidInput if format is not one of the accepted values.
	//   - Any store, graph, analysis, or rendering error.
	Run(ctx context.Context, snapshotLabel, principalARN string, maxHops int, format string, w io.Writer) error
}

// BenchmarkFacade orchestrates the full benchmark pipeline.
// Cmd/commands/benchmark.go calls exactly one method on this facade.
type BenchmarkFacade interface {
	// Run executes the full benchmark pipeline and emits a report in the
	// requested format.
	//
	// Parameters:
	//   - ctx: context for cancellation.
	//   - runID: UUIDv4 generated by the CLI at run start.
	//   - scenarioDir: path to the fixture directory containing scenario JSON files.
	//   - tools: the set of tools to invoke.
	//   - format: output format — "terminal" or "json".
	//   - w: destination for the rendered report.
	//
	// Errors:
	//   - ErrInvalidInput if format is not one of the accepted values.
	//   - ErrMissingCommitFile if fixtures/iamvulnerable/COMMIT is absent or invalid.
	//   - Any store, tool, or rendering error.
	Run(ctx context.Context, runID string, scenarioDir string, tools []model.ToolName, format string, w io.Writer) error
}

// analysisFacade is the concrete implementation of AnalysisFacade.
//
// Fields:
//   - ds: the DataStore used to load and persist analysis artifacts.
//   - policyDir: path to the directory containing OPA .rego policy files.
//   - renderers: registry mapping format identifiers to Renderer implementations.
type analysisFacade struct {
	ds        store.DataStore
	policyDir string
	renderers map[string]report.Renderer
}

// Compile-time assertion that *analysisFacade satisfies AnalysisFacade.
var _ AnalysisFacade = (*analysisFacade)(nil)

// NewAnalysisFacade returns a new AnalysisFacade backed by ds with OPA rules
// loaded from policyDir.
//
// Parameters:
//   - ds: the DataStore used to load snapshots and persist results.
//   - policyDir: filesystem path to the directory containing .rego policy files.
//   - renderers: registry mapping format identifiers to Renderer implementations;
//     pass report.NewRendererRegistry() for the standard set of renderers.
//
// Returns:
//   - An AnalysisFacade ready for use.
func NewAnalysisFacade(ds store.DataStore, policyDir string, renderers map[string]report.Renderer) AnalysisFacade {
	return &analysisFacade{ds: ds, policyDir: policyDir, renderers: renderers}
}

// Run implements AnalysisFacade.
func (f *analysisFacade) Run(ctx context.Context, snapshotLabel, principalARN string, maxHops int, format string, w io.Writer) error {
	renderer, ok := f.renderers[format]
	if !ok {
		return fmt.Errorf("analysisFacade.Run: unsupported format %q: %w", format, ErrInvalidInput)
	}

	snapshot, err := f.ds.LoadSnapshotByLabel(ctx, snapshotLabel)
	if err != nil {
		return fmt.Errorf("analysisFacade.Run: load snapshot %q: %w", snapshotLabel, err)
	}

	engine, err := graph.NewEngine(snapshot)
	if err != nil {
		return fmt.Errorf("analysisFacade.Run: build graph engine: %w", err)
	}

	if err := graph.SynthesizeEscalationEdges(engine, snapshot); err != nil {
		return fmt.Errorf("analysisFacade.Run: synthesize escalation edges: %w", err)
	}

	fromPrincipalID, err := ResolvePrincipalByARN(snapshot, principalARN)
	if err != nil {
		return fmt.Errorf("analysisFacade.Run: resolve principal ARN %q: %w", principalARN, err)
	}

	blastRadius, err := analyzer.NewAnalyzer().Analyze(ctx, engine, snapshot.ID, fromPrincipalID, maxHops)
	if err != nil {
		return fmt.Errorf("analysisFacade.Run: blast-radius analysis: %w", err)
	}

	// OPA evaluation runs in degraded mode: a failure sets PolicyEvalSkipped = true
	// and continues with Findings = nil. OPA unavailability is not a fatal error.
	var findings []*model.Finding
	var policyEvalSkipped bool
	evaluator, opaErr := policy.NewOPAEvaluator(os.DirFS(f.policyDir))
	if opaErr != nil {
		policyEvalSkipped = true
	} else {
		findings, opaErr = evaluator.Evaluate(ctx, snapshot)
		if opaErr != nil {
			policyEvalSkipped = true
			findings = nil
		}
	}

	if len(blastRadius.Paths) > 0 {
		if err := f.ds.SaveAttackPaths(ctx, blastRadius.Paths); err != nil {
			return fmt.Errorf("analysisFacade.Run: save attack paths: %w", err)
		}
	}
	if len(findings) > 0 {
		if err := f.ds.SaveFindings(ctx, findings); err != nil {
			return fmt.Errorf("analysisFacade.Run: save findings: %w", err)
		}
	}

	rpt := model.Report{
		Snapshot:          snapshot,
		BlastRadius:       blastRadius,
		Findings:          findings,
		GeneratedAt:       time.Now().UTC(),
		PolicyEvalSkipped: policyEvalSkipped,
	}

	return renderer.Render(w, &rpt)
}
